# Generated by Django 4.2.6 on 2023-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
